---
abstract: 'A bundle of MIDI and music modules'
author:
  - 'Gene Boggs <gene@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-MusicBundle
requires:
  Acme::Vuvuzela: 0
  App::Music::PlayTab: 0
  App::MusicTools: 0
  File::Format::RIFF: 0
  MIDI: 0
  MIDI::Morph: 0
  MIDI::Pitch: 0
  MIDI::Praxis::Variation: 0
  MIDI::Simple::Drummer: 0
  MIDI::SoundFont: 0
  MIDI::Tab: 0
  MIDI::Tools: 0
  MIDI::Trans: 0
  MIDI::Tweaks: 0
  Music::AtonalUtil: 0
  Music::Canon: 0
  Music::Chord::Namer: 0
  Music::Chord::Note: 0
  Music::Chord::Positions: 0
  Music::Duration: 0
  Music::Gestalt: 0
  Music::Harmonics: 0
  Music::LilyPondUtil: 0
  Music::Scales: 0
  Music::Tempo: 0
  Music::Tension: 0
  String::Approx: 0
  Text::Chord::Piano: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name={{$dist->name}}
  repository: https://github.com/ology/REPO/tree/master/{{$dist->name}}
version: 0.01
